#!/bin/bash
# NOTE: Wrapped in `{ ... }` so bash parses the whole script before executing.
{
set -e

export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

#############################
# Resume / partial-rerun helper for run_libero_plus_eval.sh
#
# Scans the per-shard results directory of an experiment, computes the
# *missing* task ranges (gaps not yet covered by any saved shard json), splits
# them into shards of SHARD_SIZE (default 100) tasks, orders them LPT-style
# (longest-per-episode suite first), and hands the resulting shard list off to
# run_libero_plus_eval.sh via the SHARDS_FILE env-var hook.
#
# Usage:
#   bash run_libero_plus_resume.sh [path/to/results_dir]
#
# If no path is given, the script defaults to the RESULTS_DIR derived from the
# POLICY_DIR below (kept in sync with run_libero_plus_eval.sh's defaults).
#############################

# Keep these aligned with run_libero_plus_eval.sh's defaults.
POLICY_CONFIG="${POLICY_CONFIG:-pi0_libero}"
POLICY_DIR="${POLICY_DIR:-checkpoints/${POLICY_CONFIG}/pi0_libero_original_4gpu/30000}"
EXP_NAME="${EXP_NAME:-$(basename "$(dirname "$POLICY_DIR")")}"
CKPT_NUM="${CKPT_NUM:-$(basename "$POLICY_DIR")}"

DEFAULT_RESULTS_DIR="data/libero_plus/results/${EXP_NAME}/${CKPT_NUM}"
RESULTS_DIR="${1:-$DEFAULT_RESULTS_DIR}"

SHARD_SIZE="${SHARD_SIZE:-100}"

if [ ! -d "$RESULTS_DIR" ]; then
    echo "ERROR: results dir not found: $RESULTS_DIR"
    echo "       Pass it as the first arg, or set POLICY_DIR/EXP_NAME/CKPT_NUM."
    exit 1
fi

echo "Scanning $RESULTS_DIR for missing shards (chunk size = $SHARD_SIZE)..."

SHARDS_FILE="$(mktemp -t libero_plus_resume_shards.XXXXXX)"

python3 - "$RESULTS_DIR" "$SHARD_SIZE" "$SHARDS_FILE" <<'PY'
import json
import os
import re
import sys

results_dir, shard_size, out_file = sys.argv[1], int(sys.argv[2]), sys.argv[3]

# These must mirror the LIBERO-Plus benchmark sizes (see task_classification.json).
SUITE_NTASKS = {
    "libero_spatial": 2402,
    "libero_object":  2518,
    "libero_goal":    2591,
    "libero_10":      2519,
}
# Used for LPT ordering: longest per-episode suite first so the long tail
# starts early and doesn't dominate the makespan.
SUITE_MAX_STEPS = {
    "libero_spatial": 220,
    "libero_object":  280,
    "libero_goal":    300,
    "libero_10":      520,
}

LPT_ORDER = sorted(SUITE_NTASKS.keys(), key=lambda s: -SUITE_MAX_STEPS[s])

def merge_intervals(intervals):
    if not intervals:
        return []
    intervals = sorted(intervals)
    out = [list(intervals[0])]
    for s, e in intervals[1:]:
        if s <= out[-1][1]:
            out[-1][1] = max(out[-1][1], e)
        else:
            out.append([s, e])
    return [tuple(x) for x in out]

def complement(covered, total):
    res, cur = [], 0
    for s, e in covered:
        if s > cur:
            res.append((cur, s))
        cur = max(cur, e)
    if cur < total:
        res.append((cur, total))
    return res

shards = []  # (suite, start, end)
print("\nCoverage report:")
print(f"  {'suite':<16} {'covered':>8} {'missing':>8}  missing intervals")
print("  " + "-" * 80)
for suite in LPT_ORDER:
    total = SUITE_NTASKS[suite]
    suite_dir = os.path.join(results_dir, suite)
    covered = []
    if os.path.isdir(suite_dir):
        for fn in os.listdir(suite_dir):
            m = re.match(r"(\d+)_(\d+)\.json$", fn)
            if m:
                covered.append((int(m.group(1)), int(m.group(2))))
    covered = merge_intervals(covered)
    missing = complement(covered, total)
    cov_n = sum(e - s for s, e in covered)
    miss_n = sum(e - s for s, e in missing)
    print(f"  {suite:<16} {cov_n:>8d} {miss_n:>8d}  {missing}")
    for ms, me in missing:
        cur = ms
        while cur < me:
            nxt = min(cur + shard_size, me)
            shards.append((suite, cur, nxt))
            cur = nxt

# LPT: keep suite groups in LPT_ORDER (already iterated that way),
# within a suite preserve ascending start (good for cache locality if any).
print(f"\nTotal missing shards: {len(shards)}")
with open(out_file, "w") as f:
    f.write("# Auto-generated by run_libero_plus_resume.sh\n")
    f.write(f"# results_dir={results_dir}\n")
    f.write(f"# shard_size={shard_size}\n")
    for s, a, b in shards:
        f.write(f"{s} {a} {b}\n")
print(f"Wrote shard list -> {out_file}")
PY

NUM_SHARDS=$(grep -vc '^[[:space:]]*\(#\|$\)' "$SHARDS_FILE" || true)
if [ "$NUM_SHARDS" -le 0 ]; then
    echo "Nothing to resume; all shards already present in $RESULTS_DIR."
    rm -f "$SHARDS_FILE"
    exit 0
fi

echo ""
echo "========== Resume plan =========="
echo "  Results dir : $RESULTS_DIR"
echo "  Shard size  : $SHARD_SIZE"
echo "  Shards      : $NUM_SHARDS"
echo "  Shard file  : $SHARDS_FILE"
echo "================================="
echo ""
echo "Shard list (LPT order):"
grep -v '^[[:space:]]*\(#\|$\)' "$SHARDS_FILE" | nl -ba | sed 's/^/  /'
echo ""

# Hand off to the main script with the explicit shard list.
# POLICY_CONFIG / POLICY_DIR are exported so the main script picks the same
# experiment when computing LOG_DIR / RESULTS_DIR.
export POLICY_CONFIG POLICY_DIR
SHARDS_FILE="$SHARDS_FILE" bash "$SCRIPT_DIR/run_libero_plus_eval.sh"

rm -f "$SHARDS_FILE"

exit 0
}
